# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install --save bootstrap@^4.0.0-alpha.6 react-bootstrap@^0.32.1 aos react-spring
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/checkout@v2
      with:
        ref: build
          
    - name: Auto committing react-app build
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "NPM BUILD to Deploy"
        branch: build
